// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Pencilera",
    platforms: [
        .iOS("17.5")
    ],
    products: [
        .iOSApplication(
            name: "Pencilera",
            targets: ["App"],
            bundleIdentifier: "org.starlightapps.pencilera",
            teamIdentifier: "3S6NT5MUQZ",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [

            ],
            capabilities: [
                .camera(purposeString: "Pencilera uses your camera to capture photos."),
                .photoLibrary(purposeString: "Pencilera needs to be able to save photos to your photo library.")
            ],
            appCategory: .photography
        )
    ],
    targets: [
        .executableTarget(
            name: "App",
            path: "App"
        )
    ]
)
